### ISSUE TITLE
Won't open Rocket app from task manager after exiting app by pressing Exit button

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#1136]
After pressing Exit button on the menu to close Rocket, users open system task manager then select Rocket to open. Current behavior is swipe out Rocket and won't open it, but UX expected behavior is open Rocket.

**Comment by haydarai** [comment]
Since the `minSdkVersion` is 21, we can use this https://developer.android.com/reference/android/app/ActivityManager.AppTask.html#finishAndRemoveTask() to exit the app and remove it from recent apps list. I'll make the changes later today.

**Comment by dakaizou** [comment]
@Jacklin-ux Can you specify the device you're using. QA's devices seemed working fine

**Comment by mTwTm** [comment]
My Sony XA can reproduce. I think I've seen it on pixel too.

**Comment by dakaizou** [comment]
It's happening on device with Android 7.0+

**Comment by Jacklin-ux** [comment]
I saw it on my Pixel phone

**Comment by walkingice** [comment]
We have `<activity-alias>` for MainActivity, and set `android:exported="false"` for **org.mozilla.focus.activity.MainActivity**.  Once we switch apps view Recent-apps, system send intent to **org.mozilla.focus.activity.MainActivity** which is not exported.

```
10-23 15:15:20.465   904  1576 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=org.mozilla.rocket.debug.jchu$
org.mozilla.focus.activity.MainActivity} from uid 10032
10-23 15:15:20.465   904  1576 W ActivityManager: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=or$
.mozilla.rocket.debug.jchu/org.mozilla.focus.activity.MainActivity } from null (pid=-1, uid=10032) not exported from uid 10164
10-23 15:15:20.469  1419  1530 E SystemServicesProxy: Could not start Firefox Rocket Dev.
10-23 15:15:20.469  1419  1530 E SystemServicesProxy: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.categor$
.LAUNCHER] flg=0x10300000 cmp=org.mozilla.rocket.debug.jchu/org.mozilla.focus.activity.MainActivity } from null (pid=-1, uid=10032) not exported from uid 10164
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at android.os.Parcel.readException(Parcel.java:1942)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at android.os.Parcel.readException(Parcel.java:1888)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at android.app.IActivityManager$Stub$Proxy.startActivityFromRecents(IActivityManager.java:8476)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at com.android.systemui.recents.misc.SystemServicesProxy.lambda$-com_android_systemui_recents_misc_SystemServicesProxy_447$
3(SystemServicesProxy.java:1193)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at com.android.systemui.recents.misc.-$Lambda$_cQrKcY7GDLaa8hAVN9aWKF9fdw$6.$m$0(Unknown Source:24)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at com.android.systemui.recents.misc.-$Lambda$_cQrKcY7GDLaa8hAVN9aWKF9fdw$6.run(Unknown Source:0)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-23 15:15:20.469  1419  1530 E SystemServicesProxy:   at java.lang.Thread.run(Thread.java:764)
```

**Comment by dakaizou** [comment]
verified in build 1641
