### ISSUE TITLE
Crash when opening screenshot links with debug option: don't keep activity

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1166]
Only crashes with don't keep activity on

STR:
1. Open My shots
2. Tap a screenshot
3. Tap open link
4. repeat 2-3, App will crash after 1~3 iterations.

**Comment by mTwTm** [comment]
10-24 13:40:25.618 19393-19393/org.mozilla.rocket.debug.tyu E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: org.mozilla.rocket.debug.tyu, PID: 19393
                                                                              java.lang.IllegalStateException: Failure saving state: ListPanelDialog{1489bab #1 } has target not in fragment manager: HomeFragment{c9a9208}
                                                                                  at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2682)
                                                                                  at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134)
                                                                                  at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:571)
                                                                                  at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
                                                                                  at android.app.Activity.performSaveInstanceState(Activity.java:1414)
                                                                                  at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1300)
                                                                                  at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4542)
                                                                                  at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3857)
                                                                                  at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3916)
                                                                                  at android.app.ActivityThread.-wrap25(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1512)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by mTwTm** [comment]
FWIW, I haven't seem something similar in our Google Play console

**Comment by mTwTm** [comment]
May relate to #258

**Comment by cynthiatang** [comment]
Verified: This issue cannot be reproduced. Thanks. :)

Device: Redmi Note4
Rocket nightly: 1.0.4 (2910). nightly
Android version: 7.0
WebView version 65.0.3325.109

**Comment by mTwTm** [comment]
Self assign: This only happens in debug build so I'd like to verify it on debug build to see if it's still there.

**Comment by mTwTm** [comment]
Can't reproduce this now :)
