### ISSUE TITLE
[Smoke Test] Rocket crashes when browsing stack empty then download via link twice

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1180]
This was fixed in #809, build 1455 works fine
STR:
1. Use Exit button to close Rocket
2. Launch Rocket
3. Visit this link [http://www.coverr.co/s3/mp4/Mobile-Games.mp4](http://www.coverr.co/s3/mp4/Mobile-Games.mp4)
4. Tap on url bar and tap go to revisit the link

Build: 1641
DuT: Samsung J7, S7 edge

**Comment by mTwTm** [comment]
10-26 10:39:29.544 13897-13897/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.mozilla.rocket.debug.tyu, PID: 13897
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                       at org.mozilla.focus.fragment.BrowserFragment$2.onProgress(BrowserFragment.java:425)
                                                       at org.mozilla.focus.webkit.WebkitView$CallbackWrapper.onProgress(WebkitView.java:332)
                                                       at org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onProgressChanged(WebkitView.java:210)
                                                       at com.android.webview.chromium.WebViewContentsClientAdapter.onProgressChanged(WebViewContentsClientAdapter.java:43)
                                                       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:79)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by mTwTm** [comment]
Oh wow this is (one of) the `null` behavior we've been finding for our whole life (?)
Here's the story:
1. The getUrl returns null initially, but no one is going to call this until a page started
2. If the url being browsed is normal url, getUrl now returns the url after is is browsed
2-1. However, if a url is a downloadurl, it will try to return to the last url being browsed, which may be null!
3. If a url is not the first url, onProgress will be called for the last url.
4. So, when we're browsing download url twice, the "go-back" step in the second url trigger may crash may occur.

**Comment by mTwTm** [comment]
Fixed in #1182

**Comment by dakaizou** [comment]
verified in build 1647
