### ISSUE TITLE
Crash when saving from webview to model

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1521]
Maybe we should do a isDestroyed check or delay the destroying of the webivew?

03-08 14:52:28.453 21559-21559/org.mozilla.rocket.debug.tyu W/cr_AwContents: Application attempted to call on a destroyed WebView
                                                                             java.lang.Throwable
                                                                                 at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:324)
                                                                                 at org.chromium.android_webview.AwContents.isDestroyedOrNoOperation(AwContents.java:296)
                                                                                 at org.chromium.android_webview.AwContents.getTitle(AwContents.java:534)
                                                                                 at com.android.webview.chromium.WebViewChromium.getTitle(WebViewChromium.java:369)
                                                                                 at android.webkit.WebView.getTitle(WebView.java:1450)
                                                                                 at org.mozilla.focus.tabs.Tab.getSaveModel(Tab.java:53)
                                                                                 at org.mozilla.focus.tabs.TabsSession.getTabModelListForPersistence(TabsSession.java:109)
                                                                                 at org.mozilla.focus.activity.MainActivity.saveTabsToPersistence(MainActivity.java:832)
                                                                                 at org.mozilla.focus.activity.MainActivity.onPause(MainActivity.java:214)
                                                                                 at android.app.Activity.performPause(Activity.java:7115)
                                                                                 at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1407)
                                                                                 at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3965)
                                                                                 at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3942)
                                                                                 at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3916)
                                                                                 at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3890)
                                                                                 at android.app.ActivityThread.-wrap15(Unknown Source:0)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by mTwTm** [comment]
Oops, this may only happen in my branch. Close it for now.
