### ISSUE TITLE
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by benjamin-cheng** [mozilla-tw/Rocket#1847]
Found in daily monkey test build: https://www.bitrise.io/build/3e21899fde7a53b5
 
FATAL EXCEPTION: AsyncQueryWorker
Process: org.mozilla.rocket.debug.bitrise, PID: 6769
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
	at org.mozilla.focus.provider.HistoryProvider.insertWithUrlUnique(HistoryProvider.java:130)
	at org.mozilla.focus.provider.HistoryProvider.insert(HistoryProvider.java:73)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:264)
	at android.content.ContentResolver.insert(ContentResolver.java:1274)
	at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:96)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by chianger** [comment]
Crash is S1 by our definition. Adding needtriage to determine priority.
