### ISSUE TITLE
Crashed - java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alc.filemanager/com.alc.filemanager.activities.MainActivity}: 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2055]
1. Launch Rocket 
2. Go to https://www.thinkbroadband.com/download
3. Tap 5GB 
4. Tap Home
5. After download completed, tap the notification for the file

Expected: 
 - No crash 

Actual result: 
 - Crashed
 - This issue cannot be reproduced in Chrome (using the same device)
 - This issue cannot be reproduced in Pixel 2 and Redmin 4 
 - https://drive.google.com/open?id=11egTUlXyubNpKPRoqj2MwW9vfux2M1Q-

Reproduced rate: 3/3

Devices
Android: 6.0.1
WebView: 66.0.3359
Rocket 2.2.0(4809).nightly

--------- beginning of crash
06-05 15:04:53.592 15386 15386 E AndroidRuntime: FATAL EXCEPTION: main
06-05 15:04:53.592 15386 15386 E AndroidRuntime: Process: com.alc.filemanager, PID: 15386
06-05 15:04:53.592 15386 15386 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alc.filemanager/com.alc.filemanager.activities.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=3; regionStart=0; regionLength=-1
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: length=3; regionStart=0; regionLength=-1
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at java.lang.String.startEndAndLength(String.java:298)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at java.lang.String.substring(String.java:1087)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at com.alc.filemanager.fragments.ZipViewer.onActivityCreated(ZipViewer.java:226)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2193)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1323)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at com.alc.filemanager.activities.MainActivity.onStart(MainActivity.java:1539)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6268)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
06-05 15:04:53.592 15386 15386 E AndroidRuntime: 	... 9 more
06-05 15:04:53.601   778  1539 W ActivityManager:   Force finishing activity com.alc.filemanager/.activities.MainActivity
06-05 15:04:53.904   778  1539 I WindowManager: Screenshot max retries 4 of Token{2499c4c ActivityRecord{e8147f u0 com.alc.filemanager/.activities.MainActivity t1067 f}} appWin=Window{7861477 u0 Starting com.alc.filemanager} drawState=4
06-05 15:04:53.904   778  1539 W ActivityManager:   Force finishing activity gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity
06-05 15:04:53.909   778  1539 I ActivityManager: Killing 11088:com.google.android.calendar/u0a31 (adj 15): empty #17
06-05 15:04:53.943   778  3098 D ActivityManager: cleanUpApplicationRecord -- 11088
06-05 15:04:54.028   778   885 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=27, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
06-05 15:04:54.405   778   791 W ActivityManager: Activity pause timeout for ActivityRecord{e8147f u0 com.alc.filemanager/.activities.MainActivity t1067 f}
06-05 15:05:01.046   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:05:02.742   778  1539 I ActivityManager: START u0 {act=android.intent.action.APP_ERROR flg=0x10000000 cmp=com.android.vending/com.google.android.finsky.activities.AppCrashProxy (has extras)} from uid 1000 on display 0
06-05 15:05:02.771   778  1313 I ActivityManager: START u0 {act=android.intent.action.APP_ERROR flg=0x10000000 pkg=com.google.android.gms cmp=com.google.android.gms/.feedback.FeedbackActivity (has extras)} from uid 10015 on display 0
06-05 15:05:02.788   778  1525 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=28, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@ab1a5d)
06-05 15:05:02.788   778   885 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=28, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
06-05 15:05:02.789   778   885 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=28, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
06-05 15:05:02.840   778  3098 I ActivityManager: Process com.alc.filemanager (pid 15386) has died
06-05 15:05:02.840   778  3098 D ActivityManager: cleanUpApplicationRecord -- 15386
06-05 15:05:02.853   778  3098 I ActivityManager: Start proc 15593:com.google.android.gms.ui/u0a7 for activity com.google.android.gms/.feedback.FeedbackActivity
06-05 15:05:02.855   778  1525 W ActivityManager: Finishing task with all activities already finished
06-05 15:05:02.855   778  1525 W ActivityManager: Duplicate finish request for ActivityRecord{116af2b u0 com.android.vending/com.google.android.finsky.activities.AppCrashProxy t1068 f}
06-05 15:05:02.936   778   799 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
06-05 15:05:07.100   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:05:19.399   778   791 I ProcessStatsService: Prepared write state in 15ms
06-05 15:05:19.624   778   790 I ProcessStatsService: Pruning old procstats: /data/system/procstats/state-2018-05-20-02-47-35.bin
06-05 15:05:28.213   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:05:43.327   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:05:46.345   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:05:52.377   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:06:28.575   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:06:37.623   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:06:57.278   778  3035 I ActivityManager: Start proc 15798:com.google.android.gms.feedback/u0a7 for service com.google.android.gms/.feedback.FeedbackAsyncService
06-05 15:06:58.046   778   961 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@99c8779}
06-05 15:06:59.054   778  1539 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@99c8779}
06-05 15:07:03.965   778  3033 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=content://downloads/all_downloads/578 typ=image/png flg=0x10000003 cmp=android/com.android.internal.app.ResolverActivity} from uid 10005 on display 0
06-05 15:07:03.991   778   788 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@d621900 attribute=null, token = android.os.BinderProxy@99b09c
06-05 15:07:09.638   778  3033 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@fadc230 attribute=null, token = android.os.BinderProxy@e128bf5
06-05 15:07:11.719   778   791 I ActivityManager: Killing 11499:com.android.defcontainer/u0a4 (adj 15): empty #17
06-05 15:07:11.796   778  3098 D ActivityManager: cleanUpApplicationRecord -- 11499
06-05 15:07:11.799   778  1522 W ActivityManager: Finishing task with all activities already finished
06-05 15:07:11.799   778  1522 W ActivityManager: Duplicate finish request for ActivityRecord{9de523d u0 android/com.android.internal.app.ResolverActivity t1070 f}
06-05 15:07:12.283   778   789 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity bnds=[12,374][276,655] (has extras)} from uid 10021 on display 0
06-05 15:07:12.537   778  3032 D ConnectivityService: listenForNetwork for Listen from uid/pid:10171/11576 for NetworkRequest [ id=29, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
06-05 15:07:29.259   778  1528 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@c793a1c attribute=null, token = android.os.BinderProxy@dab7278
06-05 15:07:32.616   778  3037 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@6ae9987 attribute=null, token = android.os.BinderProxy@dab7278
06-05 15:07:34.913   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:07:35.707   778  1973 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@1d0279e attribute=null, token = android.os.BinderProxy@dab7278
06-05 15:07:40.362   778   874 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (has extras)} from uid 1000 on display 0
06-05 15:07:42.995   778  3033 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.hecorat.screenrecorder.free/.activities.MainActivity bnds=[12,1217][276,1498] (has extras)} from uid 10021 on display 0
06-05 15:07:43.020   778  3032 I ActivityManager: Start proc 16142:com.hecorat.screenrecorder.free/u0a86 for activity com.hecorat.screenrecorder.free/.activities.MainActivity
06-05 15:07:43.749   778  3037 W WindowManager: Failed looking up window
06-05 15:07:43.749   778  3037 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@68767e8 does not exist
06-05 15:07:43.749   778  3037 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8743)
06-05 15:07:43.749   778  3037 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8734)
06-05 15:07:43.749   778  3037 W WindowManager: 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2699)
06-05 15:07:43.749   778  3037 W WindowManager: 	at com.android.server.wm.Session.remove(Session.java:187)
06-05 15:07:43.749   778  3037 W WindowManager: 	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:242)
06-05 15:07:43.749   778  3037 W WindowManager: 	at com.android.server.wm.Session.onTransact(Session.java:130)
06-05 15:07:43.749   778  3037 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:453)
06-05 15:07:43.751   778   788 I ActivityManager: START u0 {act=android.settings.action.MANAGE_OVERLAY_PERMISSION flg=0x10000000 cmp=com.hecorat.screenrecorder.free/.activities.PermissionGrantActivity} from uid 10086 on display 0
06-05 15:07:43.946   778   885 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
06-05 15:07:45.140   778  1528 I ActivityManager: START u0 {act=android.settings.action.MANAGE_OVERLAY_PERMISSION cmp=com.android.settings/.Settings$OverlaySettingsActivity} from uid 10086 on display 0
06-05 15:07:45.258   778  1313 I ActivityManager: Start proc 16248:com.android.settings/1000 for activity com.android.settings/.Settings$OverlaySettingsActivity

**Comment by cynthiatang** [comment]
This issue  can be reproduced in 
 - Focus 5.0
 - Lightning 4.5.1
 - Rocket 2.1.1(4587)

This issue cannot be reproduced in 
 - Firefox 60.0.1
 - Chrome 67.0.3396.68

 Device: Nexus5

**Comment by mTwTm** [comment]
Seems like what is crashing is the File Manager rather than Rocket. Tagging QAwanted cause I'm wondering what does it mean in "This issue cannot be reproduced in Chrome". Can the file be successfully opened with the File Manager?

**Comment by cynthiatang** [comment]
Yes, it's a crash about File Manager when opening a file which downloaded via Rocket. But I am not sure what we can do for it. 

For Chrome and Firefox, here is the video 
https://drive.google.com/open?id=1ogKSR9uLTKbmxX9PZBxamMRoazVFEdQw

**Comment by mTwTm** [comment]
With that, this bug makes much more sense. Is this only happening on 5MB file? (Also, as a side note, there's a typo in the first entry of this issue, should be 5MB instead of 5GB.)

**Comment by cynthiatang** [comment]
This is also happening on 10MB and 20MB (Thanks. I modified it  )

should be 5MB instead of 5GB.  --> yes, you are right. I modified the STR. Thanks again.

**Comment by mTwTm** [comment]
I'm also wondering what happens if you're opening it with other FIle Managers? Maybe https://play.google.com/store/apps/details?id=com.asus.filemanager If that also crashes, I would consider this as a high priority item.
