### ISSUE TITLE
Force close at launch, TabModel.id is null

### ISSUE THREAD

**Issue by mxlius** [mozilla-tw/Rocket#2189]
```
2018-07-18 18:08:01.365 15955-15955/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: gro.allizom.zelda.beta, PID: 15955
    kotlin.KotlinNullPointerException
        at org.mozilla.rocket.tabs.TabModel.isValid(TabModel.kt:30)
        at org.mozilla.rocket.tabs.TabsSession.restoreTabs(TabsSession.java:85)
        at org.mozilla.focus.activity.MainActivity.onQueryComplete(MainActivity.java:947)
        at org.mozilla.focus.persistence.TabModelStore$QueryTabsTask.onPostExecute(TabModelStore.java:123)
        at org.mozilla.focus.persistence.TabModelStore$QueryTabsTask.onPostExecute(TabModelStore.java:69)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by chianger** [comment]
this happens 100% on my Nightly, at launch.
