### ISSUE TITLE
On Android Pixel 8, when tab count is 0, can't search suggestion and show banner.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2327]
08-06 09:46:53.559 9807-10040/org.mozilla.rocket.debug.firebase W/System.err: java.net.UnknownHostException: Unable to resolve host "www.google.com": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
        at java.net.InetAddress.getAllByName(InetAddress.java:787)
        at com.android.okhttp.Dns$1.lookup(Dns.java:39)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
08-06 09:46:53.560 9807-10040/org.mozilla.rocket.debug.firebase W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
        at org.mozilla.httprequest.HttpRequest.readLines(HttpRequest.java:37)
        at org.mozilla.httprequest.HttpRequest.get(HttpRequest.java:23)
08-06 09:46:53.561 9807-10040/org.mozilla.rocket.debug.firebase W/System.err:     at org.mozilla.httptask.SimpleLoadUrlTask.doInBackground(SimpleLoadUrlTask.java:31)
        at org.mozilla.httptask.SimpleLoadUrlTask.doInBackground(SimpleLoadUrlTask.java:11)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-06 09:46:53.562 9807-10040/org.mozilla.rocket.debug.firebase W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Linux.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
    	... 26 more

**Comment by cynthiatang** [comment]
I cannot reproduce it in Pixel2. 

Video: https://drive.google.com/open?id=14nz1vS-Mo-K3d-G1CcQMsRJEjQc56-eb

Pixel 2 
Android 8.1.0
Rocket 3.0.0(6038).nightly
WebView: 68.0.3447.70

**Comment by mTwTm** [comment]
Can't reproduce on my Android 8.1 Nokia and Android 5.1 Mito.

**Comment by cynthiatang** [comment]
Can't reproduce on those devices:

Samsung
Android 8.1.0
Rocket 3.0.0(6038).nightly
WebView: 67.0.3396.68

Redmi 4X
Android 7.1
Rocket 3.0.0(6038).nightly
WebView: 67.0.3396.87

OPPO A37f
Android 5.1.1
Rocket 3.0.0(6038).nightly
WebView: 67.0.3396.87

**Comment by mTwTm** [comment]
Can't reproduce on my Android 8 Pixel, close as invalid.
