### ISSUE TITLE
Crash on Nightly when starting Rocket without Network

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2351]
java.lang.NullPointerException: Attempt to get length of null array
        at android.text.TextUtils.join(TextUtils.java:317)
        at org.mozilla.focus.home.HomeFragment.stringArrayToString(HomeFragment.java:254)
        at org.mozilla.focus.home.HomeFragment.writeToCache(HomeFragment.java:237)
        at org.mozilla.focus.home.HomeFragment.lambda$setUpBanner$0$HomeFragment(HomeFragment.java:218)
        at org.mozilla.focus.home.HomeFragment$$Lambda$2.onRootConfigLoaded(Unknown Source:6)
        at org.mozilla.focus.home.HomeFragment$LoadRootConfigTask.onPostExecute(HomeFragment.java:172)
        at org.mozilla.focus.home.HomeFragment$LoadRootConfigTask.onPostExecute(HomeFragment.java:125)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mTwTm** [comment]
Should be fixed when #2347 is merged.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel 2
Android 8.1.0
Rocket 3.0.0(6112).nightly
WebView 68.0.3440.91
