### ISSUE TITLE
Fatal Exception on first build

### ISSUE THREAD

**Issue by gaurav3017** [mozilla-tw/Rocket#2525]
`09-01 00:36:13.184 30068-30068/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.rocket.coverage, PID: 30068
    java.lang.NoSuchMethodError: No static method $$triggerInterfaceInit()V in class Lorg/mozilla/focus/utils/OnSwipeListener$$CC; or its super classes (declaration of 'org.mozilla.focus.utils.OnSwipeListener$$CC' appears in /data/app/org.mozilla.rocket.coverage-1/base.apk:classes22.dex)
        at org.mozilla.focus.home.HomeFragment$GestureListenerAdapter.<clinit>(HomeFragment.java)
        at org.mozilla.focus.home.HomeFragment.onCreateView(HomeFragment.java:332)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at org.mozilla.focus.activity.MainActivity.onStart(MainActivity.java:256)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
        at android.app.Activity.performStart(Activity.java:6915)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.access$1100(ActivityThread.java:221)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7225)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

**Comment by mTwTm** [comment]
The package name `org.mozilla.rocket.coverage` seems weird. Are you building the `focurWebkitDebug` flavor?

**Comment by mTwTm** [comment]
But yeah coverage is something we should care for too, seems like we've been ignoring it for quite a while.
