### ISSUE TITLE
[Google Play] Crash determine private or normal browsing process.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2542]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at org.mozilla.focus.FocusApplication.isInPrivateProcess(FocusApplication.kt:73)
       at org.mozilla.focus.FocusApplication.getCacheDir(FocusApplication.kt:28)
       at org.mozilla.focus.home.HomeFragment.readFromCache(HomeFragment.java:247)
       at org.mozilla.focus.home.HomeFragment.setUpBanner(HomeFragment.java:208)
       at org.mozilla.focus.home.HomeFragment.access$400(HomeFragment.java:78)
       at org.mozilla.focus.home.HomeFragment$2.onReceive(HomeFragment.java:346)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by cnevinc** [comment]
I can't find the accurate Android version. But it seems getAppRunningProcess is not [synchronous](
https://android.googlesource.com/platform/frameworks/base/+/742a67127366c376fdf188ff99ba30b27d3bf90c/core/java/android/app/ActivityManagerNative.java#2079)
If IPC fails here, it'll return a null list. 

We'll have to find a more robust way to determine if the private mode is running.
