### ISSUE TITLE
[UI Test Intermittent] restoreEmptyTab_addNewTabThenRelaunch(SaveRestoreTabsTest.java:61)

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/Rocket#2548]
See https://app.bitrise.io/build/8af847f7df7479d6

**Comment by josephyu1110** [comment]
android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: is "1"' doesn't match the selected view.
Expected: with text: is "1"
Got: "AppCompatTextView{id=2131296372, res-name=counter_text, visibility=VISIBLE, width=18, height=42, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@ab8d319, tag=null, root-is-layout-requested=false, has-input-connection=false, x=17.0, y=5.0, text=0, input-type=0, ime-target=false, has-links=false}"

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1566)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:90)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:52)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:314)
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:291)
at org.mozilla.focus.activity.SaveRestoreTabsTest.restoreEmptyTab_addNewTabThenRelaunch(SaveRestoreTabsTest.java:61)

**Comment by josephyu1110** [comment]
Test failed due to a click event turned out to be a long click event. 
<img width="1221" alt="screen shot 2018-09-06 at 2 56 42 pm" src="https://user-images.githubusercontent.com/16300853/45140374-27504800-b1e5-11e8-90ab-7f807da0f2b8.png">
