### ISSUE TITLE
[UI Test Intermittent] clickTopSite_loadTopSite(HomeTest.java:85)

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/Rocket#2549]
See https://app.bitrise.io/build/0f6e8213395d69c0

**Comment by josephyu1110** [comment]
android.support.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1566)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:90)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:52)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:291)
at org.mozilla.focus.activity.HomeTest.clickTopSite_loadTopSite(HomeTest.java:85)

**Comment by josephyu1110** [comment]
From the bitrise screenshot, looks like Espresso performs a 'long click' action instead of a 'click' action. So we can see 'Remove' is popup,  not open a webpage as what we expected.
<img width="1222" alt="screen shot 2018-09-06 at 10 49 51 am" src="https://user-images.githubusercontent.com/16300853/45132218-b730ca80-b1c2-11e8-9956-75756eef231d.png">
We can
