### ISSUE TITLE
Possible intermittent in deleteTopSite_deleteSuccessfully

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2553]
android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Remove"

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) ty=1 fl=#81810100 pfl=0x20000 wanim=0x1030465 needsMenuKey=2}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1794, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@577cd5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+-->ViewStub{id=16909288, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@f073cea, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+-->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=1794, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@88cd678, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+--->FitWindowsLinearLayout{id=2131296267, res-name=action_bar_root, visibility=VISIBLE, width=1080, height=1794, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@8afeab7, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+---->ViewStubCompat{id=2131296280, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@cf4e224, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1794, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@71e7f42, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+----->FrameLayout{id=2131296558, res-name=root, visibility=VISIBLE, width=1080, height=1794, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@8429989, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+------>FrameLayout{id=2131296327, res-name=browser, visibility=VISIBLE, width=1080, height=1794, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@2e0b49a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4}
|
+------->FrameLayout{id=2131296328, res-name=browser_container, visibility=VISIBLE, width=1080, height=1794, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3b6f0c1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+-------->View{id=2131296301, res-name=background, visibility=VISIBLE, width=1080, height=131, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@8858066, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+-------->ResizableKeyboardLayout{id=2131296477, res-name=main_content, visibility=VISIBLE, width=1080, height=1599, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@2daefa7, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=66.0, child-count=3}
|
+--------->FrameLayout{id=2131296670, res-name=webview_slot, visibility=VISIBLE, width=1080, height=1531, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.design.widget.CoordinatorLayout$LayoutParams@980d7fd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=68.0, child-count=1}
|
+---------->WebkitView{id=-1, visibility=VISIBLE, width=1080, height=1531, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3bcdf43, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+----------->FullScreenDrawerLayout{id=-1, visibility=VISIBLE, width=1080, height=1531, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.AbsoluteLayout$LayoutParams@33a363e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+------------>{id=-1, visibility=VISIBLE, width=1080, height=1531, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.v4.widget.DrawerLayout$LayoutParams@e442c9f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------------>LinearLayout{id=-1, visibility=INVISIBLE, width=1080, height=1531, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.v4.widget.DrawerLayout$LayoutParams@264cf16, tag=null, root-is-layout-requested=false, has-input-connection=false, x=-1080.0, y=0.0, child-count=6}
|
+------------->TextView{id=-1, visibility=VISIBLE, width=1080, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d091097, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=WebViewClient, input-type=0, ime-target=false, has-links=false}
|
+------------->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=43, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@e1cba6d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=57.0, child-count=1}
|
+-------------->AppCompatTextView{id=-1, visibility=VISIBLE, width=1080, height=43, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@56c6a2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=onPageStarted:m.facebook.com/, input-type=0, ime-target=false, has-links=false}
|
+------------->TextView{id=-1, visibility=VISIBLE, width=1080, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@8c41f33, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=142.0, text=BackForwardList, input-type=0, ime-target=false, has-links=false}
|
+------------->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@17502f0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=199.0, child-count=0}
|
+------------->TextView{id=-1, visibility=VISIBLE, width=1080, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b579069, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=241.0, text=View tree, input-type=0, ime-target=false, has-links=false}
|
+------------->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1233, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c7eaaee, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=298.0, child-count=0}
|
+--------->AppBarLayout{id=2131296298, res-name=appbar, visibility=VISIBLE, width=1080, height=68, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.design.widget.CoordinatorLayout$LayoutParams@d3f5e1c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+---------->FrameLayout{id=2131296661, res-name=urlbar, visibility=VISIBLE, width=1080, height=68, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.design.widget.AppBarLayout$LayoutParams@3f24008, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}
|
+----------->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=65, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@d6e18dd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4}
|
+------------>AppCompatImageButton{id=2131296378, res-name=customtab_close, desc=Return to previous app, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b621c52, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------------>AppCompatImageView{id=2131296607, res-name=site_identity, desc=Secure connection, visibility=VISIBLE, width=37, height=37, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@6d33b23, tag=null, root-is-layout-requested=false, has-input-connection=false, x=21.0, y=14.0}
|
+------------>AppCompatTextView{id=2131296397, res-name=display_url, visibility=VISIBLE, width=985, height=65, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4070820, tag=null, root-is-layout-requested=false, has-input-connection=false, x=74.0, y=0.0, text=https://m.facebook.com/, input-type=0, ime-target=false, has-links=false}
|
+------------>AppCompatImageButton{id=2131296377, res-name=customtab_actionbutton, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@43865d9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+----------->View{id=-1, visibility=VISIBLE, width=1080, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@9e1ab9e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=65.0}
|
+----------->AnimatedProgressBar{id=2131296541, res-name=progress, visibility=VISIBLE, width=1080, height=8, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@194667f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=62.0}
|
+--------->ConstraintLayout{id=2131296415, res-name=find_in_page, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.support.design.widget.CoordinatorLayout$LayoutParams@c6ff711, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=5}
|
+---------->AppCompatEditText{id=2131296544, res-name=queryText, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.support.constraint.ConstraintLayout$LayoutParams@eeb52e4, tag=null, root-is-layout-requested=false, has-input-connection=true, editor-info=[inputType=0x80001 imeOptions=0x8000005 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=Find in page label=null packageName=null fieldId=0 fieldName=null extras=null hintLocales=null ], x=0.0, y=0.0, text=, hint=Find in page, input-type=524289, ime-target=false, has-links=false}
|
+---------->AppCompatTextView{id=2131296552, res-name=resultText, desc=, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.support.constraint.ConstraintLayout$LayoutParams@dcbf34d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false}
|
+---------->AppCompatImageButton{id=2131296539, res-name=previousResult, desc=Find previous result, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.support.constraint.ConstraintLayout$LayoutParams@e863e02, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---------->AppCompatImageButton{id=2131296514, res-name=nextResult, desc=Find next result, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.support.constraint.ConstraintLayout$LayoutParams@d993313, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---------->AppCompatImageButton{id=2131296362, res-name=close_find_in_page, desc=Dismiss find in page, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.support.constraint.ConstraintLayout$LayoutParams@b7cb950, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------->View{id=-1, visibility=VISIBLE, width=1080, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@8717749, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1665.0}
|
+------->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=126, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@a59ed6f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1668.0, child-count=1}
|
+-------->EqualDistributeGrid{id=2131296329, res-name=browser_screen_menu, visibility=VISIBLE, width=870, height=105, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@babc681, tag=null, root-is-layout-requested=false, has-input-connection=false, x=105.0, y=10.0, child-count=5}
|
+--------->TabCounter{id=2131296345, res-name=btn_tab_tray, visibility=VISIBLE, width=105, height=105, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@a3b3d14, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+---------->FrameLayout{id=2131296372, res-name=counter_root, visibility=VISIBLE, width=53, height=53, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@6850703, tag=null, root-is-layout-requested=false, has-input-connection=false, x=26.0, y=26.0, child-count=2}
|
+----------->AppCompatImageView{id=2131296371, res-name=counter_box, visibility=VISIBLE, width=53, height=53, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@e191680, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+----------->AppCompatTextView{id=2131296373, res-name=counter_text, visibility=VISIBLE, width=18, height=42, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@c89c4b9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=17.0, y=5.0, text=1, input-type=0, ime-target=false, has-links=false}
|
+---------->AppCompatImageView{id=2131296370, res-name=counter_bar, visibility=VISIBLE, width=53, height=5, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@af50fe, tag=null, root-is-layout-requested=false, has-input-connection=false, x=26.0, y=82.0}
|
+--------->AppCompatImageButton{id=2131296342, res-name=btn_open_new_tab, visibility=VISIBLE, width=105, height=105, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@7c7105f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=191.0, y=0.0}
|
+--------->AppCompatImageButton{id=2131296344, res-name=btn_search, visibility=VISIBLE, width=105, height=105, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@f391aac, tag=null, root-is-layout-requested=false, has-input-connection=false, x=382.0, y=0.0}
|
+--------->AppCompatImageButton{id=2131296335, res-name=btn_capture, visibility=VISIBLE, width=105, height=105, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@e78f375, tag=null, root-is-layout-requested=false, has-input-connection=false, x=573.0, y=0.0}
|
+--------->AppCompatImageButton{id=2131296338, res-name=btn_menu, visibility=VISIBLE, width=105, height=105, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@52b7f0a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=764.0, y=0.0}
|
+------->FrameLayout{id=2131296663, res-name=video_container, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@ff6537b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0}
|
+------>FrameLayout{id=2131296364, res-name=container, visibility=VISIBLE, width=1080, height=1794, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@5733598, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0}
|
+->View{id=16908336, res-name=navigationBarBackground, visibility=VISIBLE, width=1080, height=126, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7f251f1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1794.0}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1566)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:90)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:52)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:291)
at org.mozilla.focus.activity.RemoveTopSitesTest.deleteTopSite_deleteSuccessfully(RemoveTopSitesTest.java:86)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)

**Comment by josephyu1110** [comment]
Agree with @mTwTm, we expected 'Remove' menu is popup but the top site is opened. 
<img width="1221" alt="screen shot 2018-09-06 at 2 25 12 pm" src="https://user-images.githubusercontent.com/16300853/45139168-7eecb480-b1e1-11e8-95a3-4659b9824b0d.png">
<img width="1220" alt="screen shot 2018-09-06 at 2 25 27 pm" src="https://user-images.githubusercontent.com/16300853/45139182-8613c280-b1e1-11e8-8f0a-c66349b38f2e.png">
