### ISSUE TITLE
[TopCrash] Incorrect download link inserted

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2566]
Caused by java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
       at android.content.ContentResolver.insert(ContentResolver.java:1261)
       at android.app.DownloadManager.enqueue(DownloadManager.java:1024)
       at org.mozilla.focus.download.EnqueueDownloadTask.doInBackground(EnqueueDownloadTask.java:77)
       at org.mozilla.focus.download.EnqueueDownloadTask.doInBackground(EnqueueDownloadTask.java:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by josephyu1110** [comment]
STR:
1. Settings->Apps->Show System(switch on int the action menu at the top-right corner)->DownloadManager->Disable
2. Open rocket and try to download a file

**Comment by cnevinc** [comment]
@Jacklin-ux Please advise

**Comment by josephyu1110** [comment]
I will study how to open DownloadManager settings via intent.

**Comment by Jacklin-ux** [comment]
Yes. 
My suggestion is unless we have lots of user feedback saying they can't download files and we can know the reasons. Now I would prefer do nothing as Focus does.
