### ISSUE TITLE
[Crash] Rocket crashes when trying to upload photo

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2737]
Description
Rocket Crashes when trying to upload photos 

STR:
1. Launch Rocket
2. Visit facebook and log in
3. Tap on 'photo' under avatar
4. Tap 'photo' on selection panel, then choose 'Photos' app
5. Tap back key on the top navigation bar

Expected result:
Return to previous page

Actual result:
Rocket crashes

Device info
Device: Nexus 5
OS: Android 6.0.1
WebView: 69.0.3497.100

Rocket v. 3.4.1(7489)

Clip:
https://drive.google.com/open?id=1Ku1Ufnn_CerrsKXKsacbP0xArJGgJtza

Log:
--------- beginning of crash

10-09 17:52:48.391 18588 18588 E AndroidRuntime: FATAL EXCEPTION: main

10-09 17:52:48.391 18588 18588 E AndroidRuntime: Process: org.mozilla.rocket, PID: 18588

10-09 17:52:48.391 18588 18588 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65639, result=0, data=null} to activity {org.mozilla.rocket/org.mozilla.focus.activity.MainActivity}: java.lang.IllegalStateException: Duplicate showFileChooser result

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Duplicate showFileChooser result

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at org.chromium.android_webview.AwWebContentsDelegateAdapter$2.onResult(AwWebContentsDelegateAdapter.java:4)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at com.android.webview.chromium.WebViewContentsClientAdapter$4.onReceiveValue(WebViewContentsClientAdapter.java:12)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at org.mozilla.focus.utils.FileChooseAction.onFileChose(FileChooseAction.java:57)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at org.mozilla.focus.fragment.BrowserFragment.onActivityResult(BrowserFragment.java:456)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at org.mozilla.focus.locale.LocaleAwareAppCompatActivity.onActivityResult(LocaleAwareAppCompatActivity.java:91)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at org.mozilla.focus.activity.MainActivity.onActivityResult(MainActivity.java:736)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6456)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)

10-09 17:52:48.391 18588 18588 E AndroidRuntime: 	... 9 more

10-09 17:52:48.393   795  1364 W ActivityManager:   Force finishing activity org.mozilla.rocket/org.mozilla.focus.activity.MainActivity

10-09 17:52:48.446   795 10464 I OpenGLRenderer: Initialized EGL, version 1.4

10-09 17:52:48.486  9478  9901 W arqp    : Empty context buffer. Thus might mean that the context is not synced down.

10-09 17:52:48.487  9478  9901 W armt    : Empty context model while retrieving upload opt-in status!

10-09 17:52:48.497  9478 22011 E NetworkScheduler: Invalid component specified.

10-09 17:52:48.500 26565 20870 W AdaptiveDiscoveryWorker: Exiting Adaptive Discovery. Current NetworkInfo is NULL.

10-09 17:52:48.898   795   811 W ActivityManager: Activity pause timeout for ActivityRecord{12bb109 u0 org.mozilla.rocket/org.mozilla.focus.activity.MainActivity t40 f}

10-09 17:52:48.912 21846 21846 W SearchServiceClient: Starting with NO_SESSION handoverId is deprecated. Just don't. You will break.

10-09 17:52:48.912 21846 21846 W SearchServiceClient: com.google.android.apps.gsa.shared.util.common.f: SearchServiceClient: Starting with NO_SESSION handoverId is deprecated. Just don't. You will break.

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.google.android.apps.gsa.shared.util.common.e.a(SourceFile:43)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.google.android.apps.gsa.shared.util.common.e.f(SourceFile:6)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.google.android.apps.gsa.search.shared.service.SearchServiceClient.a(SourceFile:119)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.google.android.apps.gsa.search.shared.service.SearchServiceClient.mh(SourceFile:103)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.google.android.apps.gsa.nowoverlayservice.ay.h(SourceFile:18)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.google.android.libraries.gsa.d.b.n.ao(SourceFile:17)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.google.android.libraries.gsa.d.b.n.handleMessage(SourceFile:26)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at android.os.Handler.dispatchMessage(Handler.java:98)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at android.os.Looper.loop(Looper.java:148)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at android.app.ActivityThread.main(ActivityThread.java:5417)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at java.lang.reflect.Method.invoke(Native Method)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

10-09 17:52:48.912 21846 21846 W SearchServiceClient: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

10-09 17:52:48.912 21846 21846 W SessionLifecycleManager: Handover failed. Creating new session controller.

10-09 17:52:48.926 21846 21846 E PBSessionCacheImpl: sessionId[96081263134769062] not persisted.

10-09 17:52:48.930 21846 21846 I PBSessionCacheImpl: Deleted sessionId[96081263134769062] from persistence.

10-09 17:52:48.968 21846 21846 I OptInState: There is a new client and it does not support opt-in. Dropping request.

10-09 17:52:48.990   948   948 W PathParser: Points are too far apart 4.030360828967057

10-09 17:52:48.990   948   948 W PathParser: Points are too far apart 4.030360538880159

10-09 17:52:49.005 21846 21846 I MicroDetectionWorker: #startMicroDetector [speakerMode: 0]

10-09 17:52:49.009   948   948 W PathParser: Points are too far apart 4.030360828967057

10-09 17:52:49.009   948   948 W PathParser: Points are too far apart 4.030360538880159

10-09 17:52:49.010 21846 21846 I AudioController: Created new AudioSource

10-09 17:52:49.012 21846 21846 I MicroDetectionWorker: onReady

10-09 17:52:49.025   948   948 W PathParser: Points are too far apart 4.030360828967057

10-09 17:52:49.025   948   948 W PathParser: Points are too far apart 4.030360538880159

10-09 17:52:49.026 21846  8235 I MicroRecognitionRunner: Starting detection.

10-09 17:52:49.026 21846 12967 I MicrophoneInputStream: mic_starting  SR : 16000 CC : 16 SO : 1999

10-09 17:52:49.027   200 22028 I AudioFlinger: AudioFlinger's thread 0xb2900000 ready to run

10-09 17:52:49.033 21846 12967 I MicrophoneInputStream: mic_started  SR : 16000 CC : 16 SO : 1999

10-09 17:52:49.042   200 22028 D audio_hw_primary: select_devices: out_snd_device(0: none) in_snd_device(61: voice-rec-mic)

10-09 17:52:49.042   200 22028 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(61) acdb_id(62)

10-09 17:52:49.042   200 22028 D         : Failed to fetch the lookup information of the device 0000003E 

10-09 17:52:49.042   200 22028 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19

10-09 17:52:49.042   200 22028 D audio_hw_primary: enable_snd_device: snd_device(61: voice-rec-mic)

10-09 17:52:49.042   948   948 W PathParser: Points are too far apart 4.030360828967057

10-09 17:52:49.042   948   948 W PathParser: Points are too far apart 4.030360538880159

10-09 17:52:49.045   200 22028 D audio_hw_primary: enable_audio_route: apply and update mixer path: audio-record

10-09 17:52:49.059   948   948 W PathParser: Points are too far apart 4.030360828967057

10-09 17:52:49.060   948   948 W PathParser: Points are too far apart 4.030360538880159

10-09 17:52:49.076   948   948 W PathParser: Points are too far apart 4.030360828967057

10-09 17:52:49.076   948   948 W PathParser: Points are too far apart 4.030360538880159

10-09 17:52:49.093   948   948 W PathParser: Points are too far apart 4.030360828967057

10-09 17:52:49.093   948   948 W PathParser: Points are too far apart 4.030360538880159

10-09 17:52:49.121 21846 21846 I MicroDetectionWorker: onReady

10-09 17:52:49.222 26565 20870 I DiscoveryManager: Filter criteria(null) scannerFlags(0)

10-09 17:52:49.398   193   193 W SurfaceFlinger: couldn't log to binary event log: overflow.

10-09 17:52:49.460 24968 24989 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

10-09 17:52:49.839 18588 18638 I CrashlyticsCore: Crashlytics report upload complete: 5BBC7867016F-0001-489C-0325AD08787D

10-09 17:52:51.358   200   831 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback

10-09 17:52:51.359   200   831 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)

10-09 17:52:52.255 18588 18588 I Process : Sending signal. PID: 18588 SIG: 9

10-09 17:52:52.260  5112  5112 W Binder_F: type=1400 audit(0.0:1743): avc: denied { ioctl } for path="socket:[249962]" dev="sockfs" ino=249962 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

10-09 17:52:52.260  5112  5112 W Binder_F: type=1400 audit(0.0:1744): avc: denied { ioctl } for path="socket:[249962]" dev="sockfs" ino=249962 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

10-09 17:52:52.261   200   831 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2

10-09 17:52:52.281   200   831 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)

10-09 17:52:52.281   200   831 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)

10-09 17:52:52.281   200   831 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)

10-09 17:52:52.283   200   831 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback

10-09 17:52:52.295   795  5108 I WindowState: WIN DEATH: Window{c8cf40 u0 org.mozilla.rocket/org.mozilla.focus.activity.MainActivity}

10-09 17:52:52.296   795  3477 D GraphicsStats: Buffer count: 13

10-09 17:52:52.296   795   805 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=55, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@a5208fb)

10-09 17:52:52.296   795   805 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=56, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@cc7d18)

10-09 17:52:52.297   795   900 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=55, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]

10-09 17:52:52.297   795   900 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=55, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]

10-09 17:52:52.297   795   900 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=56, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]

10-09 17:52:52.297   795   900 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=56, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]

10-09 17:52:52.341   795  3477 I ActivityManager: Process org.mozilla.rocket (pid 18588) has died

10-09 17:52:52.341   795  3477 D ActivityManager: cleanUpApplicationRecord -- 18588

10-09 17:52:52.341   795  3477 W ActivityManager: Scheduling restart of crashed service org.mozilla.rocket/org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService in 1000ms

10-09 17:52:52.446   795   816 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0

10-09 17:52:53.947 21846 12677 I EventLogSendingHelper: Sending log events.

10-09 17:52:55.479   200   831 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback

10-09 17:52:55.480   200   831 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)

10-09 17:52:56.956  9478 20875 E NetworkScheduler: Invalid component specified.

10-09 17:52:57.424  9478 22011 E NetworkScheduler: Invalid component specified.

10-09 17:52:58.959 21846 12677 I EventLogSendingHelper: Sending log events.

10-09 17:53:00.248   795   898 D WifiStateMachine: starting scan for "Macpro"WPA_PSK with 2462

10-09 17:53:04.761   795  3243 D NetlinkSocketObserver: NeighborEvent{elapsedMs=28686533, 172.20.10.1, [BACA33990564], RTM_NEWNEIGH, NUD_STALE}

10-09 17:53:16.473 22088 22088 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<

10-09 17:53:16.477 22088 22088 D AndroidRuntime: CheckJNI is OFF

10-09 17:53:16.519 22088 22088 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat

10-09 17:53:16.558 22088 22088 I Radio-JNI: register_android_hardware_Radio DONE

10-09 17:53:16.580 22088 22088 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm

10-09 17:53:16.585 22088 22088 I art     : System.exit called, status: 1

10-09 17:53:16.585 22088 22088 I AndroidRuntime: VM exiting with result code 1.

**Comment by mlwang32** [comment]
Selecting photo will also cause crash, clip:

https://drive.google.com/open?id=1McbbxjoH-ruP6wk1ek2Ra1mWKHbURqNW

**Comment by cynthiatang** [comment]
This issue can be reproduced on Sony Z3C with Android 6.0.1.
