### ISSUE TITLE
Taking screenshot crashes when Network is unavailable. (When firebase screenshot_category_manifest is set)

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2758]
Caused by java.lang.IllegalStateException: Screenshot category is not ready!
       at org.mozilla.focus.screenshot.ScreenshotManager.getCategory(ScreenshotManager.java:185)
       at org.mozilla.focus.screenshot.ScreenshotCaptureTask.doInBackground(ScreenshotCaptureTask.java:51)
       at org.mozilla.focus.screenshot.ScreenshotCaptureTask.doInBackground(ScreenshotCaptureTask.java:26)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by chianger** [comment]
QAWanted to verify if this is fixed.

**Comment by ivantw08** [comment]
verified.

Device: nexus 5
Rocket: 3.4.1(7717)
Android: 6.0
Android Webview: 69.0.3497.100
