### ISSUE TITLE
Select "Rate us" then APP force stop

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/Rocket#3022]
**Describe the bug**
Select "Rate us" then APP force stop

**Steps To Reproduce**
1. Launch Rocket and navigate through the app with the wizard steps (1st time) 
2. Make sure the "Send usage data" is disabled from rocket setting.
3. Force Stop Rocket app and launch repeatly for 5 times
4. Select "Rate us"

**Expected behavior**
Go to Google Play Store for rating

**Actual behavior**
App force stop

**Screenshots/videos**
https://drive.google.com/file/d/1iobuLlmV5cjdw8WDuDAPhS7hxbUPfrrj/view?usp=sharing

**Device info (please complete the following information):**
 - Device: Nexus 5 / Redmi 4A / Samsung S8
 - OS: Android: 6.0.1 / 7.1.2 /8.0 
 - Webview 71.0.3578.99
 - Version 1.0.5 (8877)

**Reproduce rate**
4 out of 5 times

**Additional context**
N/A

### put correct labels ###
S1

**Comment by mTwTm** [comment]
From git history the most likely regression candidate is 541fd42376ac5d0f8dfc9b7dde31b07f3caff768 (assuming 1.0.4 cannot reproduce.)

**Comment by chianger** [comment]
yes. v1.0.4 is fine. This can be reproduced with nightly v1.0.5(8905)

**Comment by mTwTm** [comment]
Confirmed regression of 541fd42
2018-12-21 17:35:45.414 27144-27144/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.rocket, PID: 27144
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter context
        at org.mozilla.focus.telemetry.TelemetryWrapper.isTelemetryEnabled(Unknown Source:2)
        at org.mozilla.focus.utils.AdjustHelper.trackEvent(AdjustHelper.java:53)
        at org.mozilla.focus.telemetry.TelemetryWrapper.clickRateApp(TelemetryWrapper.kt:1488)
        at org.mozilla.focus.utils.DialogUtils.telemetryFeedback(DialogUtils.java:110)
        at org.mozilla.focus.utils.DialogUtils.lambda$showRateAppDialog$2(DialogUtils.java:76)
        at org.mozilla.focus.utils.-$$Lambda$DialogUtils$wEBYFVSzBa1L5mrkhE3W7pluRxY.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by cnevinc** [comment]
This only happens in Release. since it didn't have Adjust implementation.

**Comment by mTwTm** [comment]
Nevin is already working on this.

**Comment by witsmo** [comment]
Verify on Firefox lite 1.0.7(9086)
Device: Redmi 4A
OS: Android 7.1.2
